class BigPauseIcon extends Icon {
    constructor() {
        super([[
            '       ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            '       ',
        ],[
            '       ',
            ' ww  ww',
            ' ww  ww',
            ' ww  ww',
            ' ww  ww',
            ' ww  ww',
            '       ',
        ],[
            '       ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            '       ',
        ],[
            '       ',
            'ww  ww ',
            'ww  ww ',
            'ww  ww ',
            'ww  ww ',
            'ww  ww ',
            '       ',
        ],[
            '       ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            '       ',
        ],[
            ' WW    ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            '    ww ',
            '       ',
        ],[
            '       ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            '       ',
        ],[
            '       ',
            '    ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww    ',
        ],[
            '       ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            '       ',
        ],[
            '    ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww    ',
            '       ',
        ],[
            '       ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            '       ',
        ],[
            '       ',
            ' ww    ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            ' ww ww ',
            '    ww ',
        ]]);
    }
}

const bigPauseIcon = new BigPauseIcon();
